### ISSUE TITLE
[Visual Bug] Tooltips may overflow the screen

### ISSUE THREAD

**Issue by nicolasferraro** [ryanckulp/10k_hours#3]
Hey! I just came across [your tweet](https://twitter.com/ryanckulp/status/1597319554090557440) introducing the project and noticed that the tooltips may overflow the screen depending on the size of the browser and I though you'd like to know. Feel free to close the issue if it's not something you want to tackle now

Really cool project BTW!

*This happened on a 4k screen with chrome occupying half of it*
<img width="1506" alt="image" src="https://user-images.githubusercontent.com/19378450/204396745-0ae81c1a-2c65-41b2-bf63-30acb71966fc.png">

**Comment by ryanckulp** [comment]
thanks @nicolasferraro ! fixed in https://github.com/ryanckulp/10k_hours/commit/3559a5efd546c2e0c0869292720ec46fc69b1ea3
